name: release-please

on:
  push:
    branches:
      - main

# permissions:
#   contents: write # to create release commit (google-github-actions/release-please-action)
#   pull-requests: write # to create release PR (google-github-actions/release-please-action)

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # only personal access token can trigger other workflows
          # The token contains at least the permissions： `contents: write` and `pull-requests: write`
          token: ${{ secrets.MY_GIT_HUB_TOKEN }}
          release-type: node
          package-name: amap-react-components
